version: "3.8"

services:
  nginx:
    image: cgr.dev/chainguard/nginx@sha256:bcc6b0d052298112e4644b258de0fa4dc1509e3df8f7c0fba09e8c92987825e7
    volumes:
      - ./nginx.codeleap.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    networks:
      - main
    logging:
      driver: ${LOGGING}

  django:
    environment:
      - MIGRATE=${MIGRATE}
      - TEST=${TEST}
    build: .
    networks: 
      - main

  postgres:
    image: cgr.dev/chainguard/postgres@sha256:61d7206d55e60ebc60e881f1cc8f05600c1e1ca89a3535595520d0739404d531
    environment:
      POSTGRES_DB: codeleap
      POSTGRES_USER: codeleap
      POSTGRES_PASSWORD: codeleap
    volumes:
      - data:/var/lib/postgresql/data
    networks: 
      - main
    ports:
      - "5432:5432"
    logging:
      driver: ${LOGGING}

networks:
  main:
volumes:
  data: