# Generated by Django 5.0.2 on 2024-02-27 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrers',
            new_name='Careers',
        ),
        migrations.AlterModelOptions(
            name='careers',
            options={'ordering': ['created_datetime']},
        ),
    ]
